### ISSUE TITLE
Namespace exist in the Cluster 

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/terraform-gitops-cp-sterling-oms#4]
After destroy, the namespace still exist in the cluster as well as 2 entries in the ARGO CD
<img width="317" alt="Screen Shot 2022-04-14 at 6 19 14 PM" src="https://user-images.githubusercontent.com/25986944/163492380-0a27328d-13c6-4941-ad67-ce91d6be9e9d.png">

<img width="1205" alt="Screen Shot 2022-04-14 at 6 17 34 PM" src="https://user-images.githubusercontent.com/25986944/163492281-3e496eb5-c7cf-4f17-9637-085bc6d24472.png">

**Comment by balasgit** [comment]
- Need to explore why projects are not getting deleted from ROKS Cluster as artifacts are removed from ARGOCD  during Destroy

**Comment by balasgit** [comment]
Added Delete namespace to the Kubernetes which removed from Cluster.

**Comment by PriyaVasudevan** [comment]
Doesn't look to be a OMS issue.

**Comment by balasgit** [comment]
Added clean up scripts to the project which helped to delete if we re-run
